### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.


# Programa Ingenias+ Data Science

In [ ]:
#Importar numpy
import numpy as np

In [ ]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
np.zeros(shape = (2,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#prueba: arreglo de unos de longitud 5
a = np.ones(5)

print(a)

[1. 1. 1. 1. 1.]


In [ ]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arreglo = np.zeros(10)
arreglo[4] = 10

print(arreglo)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
arreglo = np.ones(10)
arreglo[2] = 7

print(arreglo)

[1. 1. 7. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array = np.arange(10,49,1)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
array = np.arange(0, 9)
array = array.reshape(3, 3)

print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array = np.random.rand(100)

media = array.mean()
varianza = array.var()

print("Media:", media)
print("Varianza:", varianza)

Media: 0.46710264268793844
Varianza: 0.07848329353081578


In [ ]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
array = np.random.rand(25)
media = array.mean()
varianza = array.var()
print("Media:", media)
print("Varianza:", varianza)

Media: 0.5157394228093907
Varianza: 0.08897468102720142


In [ ]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
arreglo = np.array([10, 20, 30, 40, 50])

media = np.sum(arreglo) / len(arreglo)

print("Media:", media)

Media: 30.0


In [ ]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
arreglo = np.array([2, 4, 6, 8, 10])

media = np.mean(arreglo)

varianza = np.sum((arreglo - media) ** 2) / len(arreglo)

print("Media:", media)
print("Varianza:", varianza)

Media: 6.0
Varianza: 8.0


In [ ]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

array = np.random.randn(10)

print(array)

[ 0.60453707  0.73098699 -1.21360894  1.10038371 -0.15507977  1.27095702
  0.31683844  0.80591223 -1.0543208   0.94766469]


np.random.randn() -> sirve para generar números aleatorios siguiendo una distribución normal estándar. Por ejemplo, para crear un array de 10 números